USE GD2C2022
GO

-- DROP FUNCIONES ------------------------------------------------------------

-- DROP DE VIEWS ----------------------------------------------------------------

-- DROP TABLAS DIMENSIONALES ---------------------------------------------------------------

IF OBJECT_ID('SE_APRUEBA_GDD.BI_FECHA') IS NOT NULL
  DROP TABLE SE_APRUEBA_GDD.BI_FECHA
  GO

IF OBJECT_ID('SE_APRUEBA_GDD.BI_PROVINCIA') IS NOT NULL
  DROP TABLE SE_APRUEBA_GDD.BI_PROVINCIA
  GO

IF OBJECT_ID('SE_APRUEBA_GDD.BI_RANGO_ETARIO') IS NOT NULL
  DROP TABLE SE_APRUEBA_GDD.BI_RANGO_ETARIO
  GO

IF OBJECT_ID('SE_APRUEBA_GDD.BI_CANAL_VENTA') IS NOT NULL
  DROP TABLE SE_APRUEBA_GDD.BI_CANAL_VENTA
  GO

IF OBJECT_ID('SE_APRUEBA_GDD.BI_MEDIO_PAGO_VENTA') IS NOT NULL
  DROP TABLE SE_APRUEBA_GDD.BI_MEDIO_PAGO_VENTA
  GO

IF OBJECT_ID('SE_APRUEBA_GDD.BI_MEDIO_PAGO_COMPRA') IS NOT NULL
  DROP TABLE SE_APRUEBA_GDD.BI_MEDIO_PAGO_COMPRA
  GO

IF OBJECT_ID('SE_APRUEBA_GDD.BI_CATEGORIA') IS NOT NULL
  DROP TABLE SE_APRUEBA_GDD.BI_CATEGORIA
  GO

IF OBJECT_ID('SE_APRUEBA_GDD.BI_PRODUCTO') IS NOT NULL
  DROP TABLE SE_APRUEBA_GDD.BI_PRODUCTO
  GO

IF OBJECT_ID('SE_APRUEBA_GDD.BI_TIPO_DESCUENTO') IS NOT NULL
  DROP TABLE SE_APRUEBA_GDD.BI_TIPO_DESCUENTO
  GO

IF OBJECT_ID('SE_APRUEBA_GDD.BI_TIPO_ENVIO') IS NOT NULL
  DROP TABLE SE_APRUEBA_GDD.BI_TIPO_ENVIO
  GO

IF OBJECT_ID('SE_APRUEBA_GDD.BI_CLIENTE') IS NOT NULL
  DROP TABLE SE_APRUEBA_GDD.BI_CLIENTE
  GO

IF OBJECT_ID('SE_APRUEBA_GDD.BI_PROVEEDOR') IS NOT NULL
  DROP TABLE SE_APRUEBA_GDD.BI_PROVEEDOR
  GO


-- DROP TABLAS DE HECHOS ---------------------------------------------------------------

IF OBJECT_ID('SE_APRUEBA_GDD.BI_VENTA') IS NOT NULL
  DROP TABLE SE_APRUEBA_GDD.BI_VENTA
  GO

IF OBJECT_ID('SE_APRUEBA_GDD.BI_COMPRA') IS NOT NULL
  DROP TABLE SE_APRUEBA_GDD.BI_COMPRA
  GO

-- DROP PROCEDURES DE MIGRACION DE TABLAS DIMENSIONALES ---------------------------------------------------------------

-- DROP PROCEDURES DE MIGRACION DE TABLAS DE HECHOS ---------------------------------------------------------------

-- DROP ESQUEMA

IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'SE_APRUEBA_GDD')
    DROP SCHEMA SE_APRUEBA_GDD
GO


-- CREACION ESQUEMA

CREATE SCHEMA SE_APRUEBA_GDD -- Después de authorization vá la contraseña

GO

-- CREACIÓN TABLAS DIMENSIONALES


create table SE_APRUEBA_GDD.BI_FECHA (
    FECHA_ID decimal(19,0),
    FECHA_AÑO decimal(19,0),
	FECHA_MES decimal(19,0),
	PRIMARY KEY (FECHA_ID)
);


create table SE_APRUEBA_GDD.BI_PROVINCIA (
	PROVINCIA_ID decimal(19,0) identity(1,1),
	PROVINCIA_NOMBRE nvarchar(255),
	PRIMARY KEY (PROVINCIA_ID) 
);


create table SE_APRUEBA_GDD.BI_RANGO_ETARIO (
    RANGO_ID decimal(19,0) identity(1,1),
    RANGO_EDAD_INI decimal(19,0),
    RANGO_EDAD_FIN decimal(19,0),
    PRIMARY KEY (RANGO_ID) 
);

create table SE_APRUEBA_GDD.BI_CANAL_VENTA (
	CANAL_VENTA_ID decimal(19, 0) identity(1,1),
	CANAL_VENTA_TIPO nvarchar(2255),
	CANAL_VENTA_COSTO decimal(18,2),
	PRIMARY KEY (CANAL_VENTA_ID)
);

create table SE_APRUEBA_GDD.BI_MEDIO_PAGO_COMPRA (
	MEDIO_PAGO_ID decimal(19, 0) identity(1,1),
	MEDIO_PAGO_TIPO nvarchar(255),
	PRIMARY KEY (MEDIO_PAGO_ID)
)

create table SE_APRUEBA_GDD.BI_MEDIO_PAGO_VENTA (
	MEDIO_PAGO_ID decimal(19,0) identity(1,1),
	MEDIO_PAGO_TIPO nvarchar(255),
	MEDIO_PAGO_COSTO decimal(18,2),
	MEDIO_PAGO_DESCUENTO decimal(18, 2),
	PRIMARY KEY (MEDIO_PAGO_ID)
);

create table SE_APRUEBA_GDD.BI_CATEGORIA (
	CATEGORIA_ID decimal(19,0) identity(1,1),
	CATEGORIA_DESCRIPCION nvarchar(50),
	PRIMARY KEY (CATEGORIA_ID)
);

create table SE_APRUEBA_GDD.BI_PRODUCTO (
	PRODUCTO_ID nvarchar(50),
	PRODUCTO_DESCRIPCION nvarchar(50),
	PRODUCTO_NOMBRE nvarchar(50),
	PRODUCTO_MARCA decimal(19,0),
	PRODUCTO_CATEGORIA decimal(19,0),
	PRODUCTO_MATERIAL decimal(19,0),
	PRIMARY KEY (PRODUCTO_ID),
	FOREIGN KEY (PRODUCTO_MARCA) REFERENCES SE_APRUEBA_GDD.MARCA(MARCA_ID),
	FOREIGN KEY (PRODUCTO_CATEGORIA) REFERENCES SE_APRUEBA_GDD.CATEGORIA(CATEGORIA_ID),
	FOREIGN KEY (PRODUCTO_MATERIAL) REFERENCES SE_APRUEBA_GDD.MATERIAL(MATERIAL_ID)
);

/* TODO: Crear tabla tipo descuento

create table SE_APRUEBA_GDD.BI_TIPO_DESCUENTO ();

*/

create table SE_APRUEBA_GDD.BI_ENVIO_VENTA (
	ENVIO_VENTA_ID decimal(19,0) identity(1,1),
	ENVIO_VENTA_TIPO nvarchar(255),
	ENVIO_VENTA_PRECIO decimal(18,2),
	PRIMARY KEY (ENVIO_VENTA_ID)
);

create table SE_APRUEBA_GDD.BI_CLIENTE (
	CLIENTE_ID decimal(19, 0) identity(1,1),
	CLIENTE_NOMBRE nvarchar(255),
	CLIENTE_APELLIDO nvarchar(255),
	CLIENTE_DNI decimal(18, 0),
	CLIENTE_DIRECCION nvarchar(255),
	CLIENTE_TELEFONO decimal(18,0),
	CLIENTE_MAIL nvarchar(255),
	CLIENTE_FECHA_NAC date,
	PRIMARY KEY (CLIENTE_ID)
);

create table SE_APRUEBA_GDD.BI_PROVEEDOR (
	PROVEEDOR_CUIT nvarchar(50),
	PROVEEDOR_RAZON_SOCIAL nvarchar(50),
	PROVEEDOR_DOMICILIO nvarchar(50),
	PROVEEDOR_MAIL nvarchar(50),
	PRIMARY KEY (PROVEEDOR_CUIT)
);

-- CREACIÓN TABLAS HECHOS

create table SE_APRUEBA_GDD.BI_VENTA (
    FECHA_ID decimal(19,0),
    CLIENTE_ID decimal(19, 0),
    RANGO_ID decimal(19,0),
    MEDIO_PAGO_ID decimal(19,0),
    CANAL_VENTA_ID decimal(19, 0),
    PROVINCIA_ID decimal(19,0),
    PRODUCTO_ID nvarchar(50),


);

create table SE_APRUEBA_GDD.BI_COMPRA (
    FECHA_ID decimal(19,0),
    PROVEEDOR_CUIT decimal(19, 0),
    MEDIO_PAGO_ID decimal(19,0),
    CANAL_VENTA_ID decimal(19, 0),
    PROVINCIA_ID decimal(19,0),
    PRODUCTO_ID nvarchar(50),

);